version: 1.0.{build}
os:
- WMF 5
configuration: Release
platform: Any CPU
# Install Pester
install: 
    - cinst -y pester
    - ps: install-package -ProviderName PowerShellGet -Name SCOrchDev-Utility
clone_folder: c:\git\PowerShellModules
build: false

test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}